# Generated by Django 2.0.13 on 2019-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.CharField(default='USA', max_length=20),
            preserve_default=False,
        ),
    ]
