# Generated by Django 2.0.13 on 2019-06-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0002_company_company_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Primes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
