# Generated by Django 2.0.13 on 2019-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0003_primes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primes',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
