# Generated by Django 2.0.13 on 2019-06-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0004_auto_20190601_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Primes',
            new_name='PrimeNumber',
        ),
    ]
