# Generated by Django 2.0.13 on 2019-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0005_auto_20190602_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primenumber',
            name='value',
            field=models.IntegerField(),
        ),
    ]
