# Generated by Django 2.0.13 on 2019-06-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0006_auto_20190602_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnorderedPrimeNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
