# Generated by Django 2.0.13 on 2019-07-01 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0008_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_id',
            new_name='job_PO',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='client',
            new_name='job_company',
        ),
        migrations.AddField(
            model_name='company',
            name='company_abbr',
            field=models.CharField(default='--', max_length=5, unique=True, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_ref',
            field=models.CharField(default='r', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_startdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_country',
            field=models.CharField(max_length=20, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Corporate name'),
        ),
    ]
