# Generated by Django 2.0.13 on 2019-07-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0010_company_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.TextField(verbose_name='Corporate address'),
        ),
    ]
