# Generated by Django 2.0.13 on 2019-07-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0011_auto_20190701_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_abbr',
        ),
    ]
