# Generated by Django 2.0.13 on 2019-07-01 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0013_auto_20190701_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='Invoice No.')),
                ('invoice_date', models.DateField(default=datetime.date.today, verbose_name='Invoice date')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_short_name', models.CharField(max_length=50, unique=True, verbose_name='Payment method')),
                ('method_info', models.TextField(verbose_name='Payment information')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson1.Invoice'),
        ),
    ]
